config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  get "/about" => "home#about", as: :about


  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :projects do
    post "/projects/search" => "projects#search"
    resources :tasks#, shallow: true
    resources :discussions
  end

  resources :discussions do
    resources :comments #, shallow: true
  end

  root "home#index"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :description, presence: {message: "his message is from discussion model"}
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authorize!, only: [:destroy, :update, :edit]
  before_action :load_discussion_and_authorize!, only: [:destroy, :update, :edit]


  def create
    @project          = Project.find params[:project_id]
    # @discussion       = @project.discussions.new params.require(:discussion).permit(:description, :title)

    @discussion = Discussion.new params.require(:discussion).permit(:description, :title)
    @discussion.project_id = @project.id

    @tasks = @project.tasks
    @discussions = @project.discussions

    if @discussion.save
      redirect_to project_path(@project), notice: "discussion created!"
    else
      render "/projects/show", notice: "Error"
    end
  end

  def show
    @discussion = Discussion.find params[:id]
    @comments = @discussion.comments
    @comment = Comment.new
  end

  def destroy
    @project = Project.find params[:project_id]
    # @discussion = Discussion.find params[:id]
    @discussion.destroy
    redirect_to project_path(@project), notice: "Discussion deleted"
  end

  def edit
    @project = Project.find params[:project_id]
    # @discussion = Discussion.find params[:id]
  end

  def update
    # @discussion = Discussion.find params[:id]
    if @discussion.update discussion_params
      redirect_to project_path(@discussion.project_id)
    else
      render :edit
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit([:title, :description])
  end

  def load_discussion_and_authorize!
    @discussion = Discussion.find params[:id]
    redirect_to root_path, alert: "access denied" unless @discussion.user == current_user
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/edit.html.erb
<h1>Edit Discussion</h1>
<%= @discussion.errors.full_messages.join(", ") %>
  <%= form_for [@project, @discussion] do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit %>
  <% end  %>

app/views/discussions/show.html.erb
<h1>Discussion</h1>
<div>
<%= @discussion.title %>
</div>
<%= @discussion.description%>

<hr>

<h2>Add comment</h2>
<%= form_for [@discussion, @comment] do |c|%>
<div>
  <%= c.label :body %>
  <%= c.text_area :body %>
</div>
<%= c.submit %>
<% end %>

<hr>

<h2>Comments</h2>
<% @discussion.comments.each do |com| %>
<div>
<%= com.body %>

<%= link_to "edit", edit_discussion_comment_path(@discussion, com) %> |
<%= link_to "delete", [@discussion, com],method: :delete, data: {confirm: "Are you sure?"} %>
<hr>
</div>
<% end %>