config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  get "/about" => "home#about", as: :about


  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :projects do
    post "/projects/search" => "projects#search"
    resources :tasks#, shallow: true
    resources :discussions
  end

  resources :discussions do
    resources :comments #, shallow: true
  end

  root "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  after_initialize :set_status_default

  belongs_to :project
  validates :title, presence: true

  def set_status_default
    self.status ||= false
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize!, only: [:destroy, :update, :edit]
  before_action :load_task_and_authorize!, only: [:destroy, :update, :edit]

  def new
    @task = Task.new
    @project = Project.find params[:project_id]
  end

  def create
    @task = Task.new params.require(:task).permit(:title)
    @project = Project.find params[:project_id]
    @task.project = @project
    if @task.save
      redirect_to project_path(@project), notice: 'Successful'
    else
      render :new, alert: 'Unsuccessful'
      # redirect_to project_path(@project), alert: 'Unsuccessful'
    end
  end

  def show
    @task = Task.find params[:id]
    @project = Project.find params[:project_id]
    if params[:id]
      @task = Task.find params[:id]
      @task.status == false ? @task.status = true : @task.status = false
      @task.save
    end
    redirect_to project_path(@project)
  end

  def index
    @tasks = Task.all

  end

  def edit
    # @task = Task.find params[:id]
    @project = Project.find params[:project_id]
  end

  def update
    @project = Project.find params[:project_id]
    task_params = params.require(:task).permit(:title)
    # @task = Task.find params[:id]
    if @task.update task_params
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    project = Project.find params[:project_id]
    task = Task.find params[:id]
    task.destroy
    redirect_to project_path(project.id)
  end

  private

  def load_task_and_authorize!
    @task = Task.find params[:id]
    redirect_to root_path, alert: "access denied" unless @task.user == current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= @task.errors.full_messages.join(", ") %>
<%= form_for [@project,@task] do |task| %>
  <div>
    <%= task.label :title %>
    <%= task.text_field :title %>
  </div>
  <%= task.submit %>
<% end  %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<% @tasks.each do |task| %>
<div>
  <h2><%= link_to task.title, task_path(task) %></h2>
  <hr>
</div>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<% if @task.errors.any? %>
<ul>
  <% @task.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [@project,@task] do |task| %>
<div>
  <%= task.label :title %>
  <%= task.text_field :title %>
</div>
<%= task.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.created_at %></p>
<%= link_to "Edit", edit_task_path(@task) %>
<%= link_to "Delete", task_path(@task), method: :delete, data: {confirm: "Are you sure?"} %>