config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  get "/about" => "home#about", as: :about


  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :projects do
    post "/projects/search" => "projects#search"
    resources :tasks#, shallow: true
    resources :discussions
  end

  resources :discussions do
    resources :comments #, shallow: true
  end

  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  # after_initialize :set_status_default

  has_many :discussions, dependent: :destroy
  has_many :tasks, dependent: :destroy
  validates :title, presence: {message: "his message is from project model1"}
  validates :description, presence: {message: "his message is from project model2"}

  belongs_to :user
  # def set_status_default
  #   self.status ||= false
  # end

  def self.search(search_term)
    where(["title ILIKE ? OR description ILIKE?", "%#{search_term}%", "%#{search_term}%"])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_project_and_authorize!, only: [:destroy, :update, :edit]
  PROJECTS_PER_PAGE = 7

  def index
    @projects2 = Project.search(params[:search_term])
    @projects = @projects2.order(created_at: :desc).
                           page(params[:page]).
                           per(PROJECTS_PER_PAGE)
  end

  def show
    @project = Project.find params[:id]
    @projects2 = Project.search(params[:search_term])
    @projects = @projects2.order(created_at: :desc).
                           page(params[:page]).
                           per(PROJECTS_PER_PAGE)
    @tasks = @project.tasks.order(:title)
    @discussions = @project.discussions

    @discussion = Discussion.new
    # @discussion = @project.discussions.new

    # if params[:id]
    #   @task = @project.tasks
    #   @task.status == false ? @task.status = true : @task.status = false
    #   @task.save
    # end

    # @comment = Comment.new
  end

  def edit
    @task = Task.find params[:id]
  end

  def new
    @task = Task.new
    @project = Project.new
  end

  def update
    if @project.update project_params
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to project_path
  end

  def create
    @project = Project.new project_params
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project), notice: "Project created successfully"
    else
      flash[:alert] = "Please fix errors below before saving"
      render :new
    end
  end

  def project_params
    params.require(:project).permit([:title, :description])
  end

  def search
    if params[:search_term]
      query = "%#{params[:search_term]}%"
      @projects = Project.where(
      "title ILIKE :search_term OR description ILIKE :search_term",
      {search_term: query}
      )
    else
      @projects = Project.all
    end
      render :index
  end

  private

  def load_project_and_authorize!
    @project = Project.find params[:id]
    redirect_to root_path, alert: "access denied" unless @project.user == current_user
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= @project.errors.full_messages.join(", ") %>
  <%= form_for @project do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit %>
  <% end  %>

app/views/projects/index.html.erb
<h1>Project lists</h1>
<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
    </tr>
  </thead>
  <% @projects.each do |project| %>
    <tbody>
      <tr>
        <td><%= link_to project.title, project_path(project) %></td>
        <td><%= project.description %></td>
        <td><%= link_to "Edit", edit_project_path(project) %>
        <%= link_to "Delete", project_path(project),
                                method: :delete,
                                data: {confirm: "Are you sure?"}%></td>
      </tr>
    </tbody>
  <% end %>

</table>

<div class="digg_pagination">
  <%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<h1>Create new project</h1>

<%= form_for @project do |f| %>
<div>
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div>
<%= f.label :description %>
<%= f.text_field :description %>
</div>
<%= f.submit "create project"%>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p>
  <%= @project.description %>
</p>
<hr>
<div>
  <h3>Tasks</h3>
  <% @tasks.each do |task| %>
  <h4><%= task.title %></h4>
  <%# task.updated_at %>
  <%= link_to "Edit", edit_project_task_path(@project,task) %>
  <%= link_to "Delete", project_task_path(@project,task), method: :delete, data: {confirm: "Are you sure?"} %>
  <% if task.status == false %>
        <%= link_to "Not Done", project_task_path(@project,task), class: "btn not-done" %>
      <% else %>
        <%= link_to "Done", project_task_path(@project,task), class: "btn done" %>
      <% end %>
  <% end %>
</div>
<%= link_to "New task", new_project_task_path(@project) %>

<hr>
<h3>Create Discussion</h3>
<%= @discussion.errors.full_messages.join(", ") %>
<%= form_for [@project, @discussion] do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_area :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<%= f.submit %>
<% end %>

<hr>

<h2>Discussions</h2>
<% @discussions.each do |disc| %>
    <h4><%= disc.title %></h4>
    <%= disc.description %>
    <%= link_to "add comment", project_discussion_path(disc.project, disc)  %> |
    <%= link_to "edit", edit_project_discussion_path(@project, disc) %> |
    <%= link_to "Delete", [@project, disc], method: :delete, data: {confirm: "Are you sure?"} %>
  <hr>
<% end %>