config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  get "/about" => "home#about", as: :about


  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :projects do
    post "/projects/search" => "projects#search"
    resources :tasks#, shallow: true
    resources :discussions
  end

  resources :discussions do
    resources :comments #, shallow: true
  end

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to("Home", root_path) %>
    <!-- <a href="<%= root_path %>">Home</a> -->
    |
    <%= link_to "About", about_path%>
    <!-- <a href="/about">About</a> -->
    |
    <%= link_to "New project", new_project_path %>
    |
    <%= link_to "Projects", projects_path %>
    <!-- | -->
    <%# link_to "Tasks", tasks_path %>
    <!-- | -->
    <%# link_to "New task", new_task_path %>
    |
  <div>
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", sessions_path, method: "delete" %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", new_session_path %>
    <% end %>
  </div>
  <div>
    <%= form_tag projects_path, :method => 'get' do %>
    <%= text_field_tag :search_term, params[:search_term] %>
    <%= submit_tag "Search"%>
<!-- <%# submit_tag "Search", :name => nil %> why is there :name => nil ? I don't know-->
    <% end %>
  </div>

    <hr>
    <center><%= flash[:alert] || flash[:notice]%></center>
    <%= yield %>
  </body>
</html>